### PR TITLE
Adds temperature and fan readings from lm_sensors

### LINKED ISSUE #34: Remove static linking for binaries
The initial idea was to ship the binaries with the report. This doesn't work so we can remove the static linking

### PR DESCRIPTION
**Pull request by ribalba**
Closes #34

### CODE REVIEW

**Comment by ribalba** [comment]
I added https://github.com/green-coding-berlin/green-metrics-tool/issues/34 into this commit.

**Comment by ArneTR** [comment]
Running into issues: 

```
gcc source.c chips.c -o3 -Wall -Llib -lsensors -o metric-provider-binary
source.c:44:10: fatal error: sensors/sensors.h: No such file or directory
   44 | #include "sensors/sensors.h"
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from chips.c:34:
chips.h:30:10: fatal error: sensors/sensors.h: No such file or directory
   30 | #include "sensors/sensors.h"
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:4: metric-provider-binary] Error 1
make: Leaving directory '/home/arne/Sites/green-coding/green-metrics-tool/tools/metric_providers/lm_sensors'
```

where is the sensors.h supposed to be?

I have lm-sensors installed but I cannot find any sensors.h on my system:

```
❯ find / 2>/dev/null | grep sensors.h
/usr/lib/modules/5.15.0-48-generic/kernel/drivers/iio/common/hid-sensors/hid-sensor-trigger.ko
/usr/lib/modules/5.15.0-48-generic/kernel/drivers/iio/common/hid-sensors/hid-sensor-iio-common.ko
/usr/lib/modules/5.15.0-52-generic/kernel/drivers/iio/common/hid-sensors/hid-sensor-trigger.ko
/usr/lib/modules/5.15.0-52-generic/kernel/drivers/iio/common/hid-sensors/hid-sensor-iio-common.ko
/usr/src/linux-headers-5.15.0-48/include/linux/iio/common/ssp_sensors.h
/usr/src/linux-headers-5.15.0-48/include/linux/iio/common/st_sensors.h
/usr/src/linux-headers-5.15.0-52/include/linux/iio/common/ssp_sensors.h
/usr/src/linux-headers-5.15.0-52/include/linux/iio/common/st_sensors.h
```

**Comment by ribalba** [comment]
Did you run
```
sudo apt install lm-sensors libsensors-dev 
```

https://github.com/green-coding-berlin/documentation/blob/main/content/en/docs/installation/installation-overview.md#setting-up-your-machine

**Comment by ArneTR** [comment]
That one I missed. We are one step closer. Next error:

```
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 0_o >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


Error:  RuntimeError occured in runner.py:  Stderr on LmSenorsCpuTempProvider was NOT empty: b'No sensor feature found!\n' 25316eed-43e0-4f38-ac72-4e8296a98e1a


<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 0_o >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


Traceback (most recent call last):
  File "/home/arne/Sites/green-coding/green-metrics-tool/tools/runner.py", line 436, in <module>
    runner.run(uri=args.uri, uri_type=uri_type, project_id=project_id) # Start main code
  File "/home/arne/Sites/green-coding/green-metrics-tool/tools/runner.py", line 256, in run
    raise RuntimeError(f"Stderr on {metric_provider.__class__.__name__} was NOT empty: {stderr_read}")
RuntimeError: Stderr on LmSenorsCpuTempProvider was NOT empty: b'No sensor feature found!\n'


<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 0_o >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
```

It looks like the error you had during presenting the feature and then you did a hotfix. Did you push that?

**Comment by ArneTR** [comment]
Here is the output as requested from our cloud machine:

```
coretemp-isa-0001
Adapter: ISA adapter
Package id 1:  +47.0°C  (high = +85.0°C, crit = +95.0°C)
Core 0:        +41.0°C  (high = +85.0°C, crit = +95.0°C)
Core 1:        +41.0°C  (high = +85.0°C, crit = +95.0°C)
Core 2:        +45.0°C  (high = +85.0°C, crit = +95.0°C)
Core 3:        +41.0°C  (high = +85.0°C, crit = +95.0°C)
Core 4:        +41.0°C  (high = +85.0°C, crit = +95.0°C)
Core 5:        +43.0°C  (high = +85.0°C, crit = +95.0°C)
Core 8:        +43.0°C  (high = +85.0°C, crit = +95.0°C)
Core 9:        +42.0°C  (high = +85.0°C, crit = +95.0°C)
Core 10:       +46.0°C  (high = +85.0°C, crit = +95.0°C)
Core 11:       +41.0°C  (high = +85.0°C, crit = +95.0°C)
Core 12:       +45.0°C  (high = +85.0°C, crit = +95.0°C)
Core 13:       +43.0°C  (high = +85.0°C, crit = +95.0°C)

power_meter-acpi-0
Adapter: ACPI interface
power1:       58.00 W  (interval =   1.00 s)

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +49.0°C  (high = +85.0°C, crit = +95.0°C)
Core 0:        +45.0°C  (high = +85.0°C, crit = +95.0°C)
Core 1:        +43.0°C  (high = +85.0°C, crit = +95.0°C)
Core 2:        +42.0°C  (high = +85.0°C, crit = +95.0°C)
Core 3:        +41.0°C  (high = +85.0°C, crit = +95.0°C)
Core 4:        +42.0°C  (high = +85.0°C, crit = +95.0°C)
Core 5:        +43.0°C  (high = +85.0°C, crit = +95.0°C)
Core 8:        +41.0°C  (high = +85.0°C, crit = +95.0°C)
Core 9:        +43.0°C  (high = +85.0°C, crit = +95.0°C)
Core 10:       +43.0°C  (high = +85.0°C, crit = +95.0°C)
Core 11:       +42.0°C  (high = +85.0°C, crit = +95.0°C)
Core 12:       +41.0°C  (high = +85.0°C, crit = +95.0°C)
Core 13:       +44.0°C  (high = +85.0°C, crit = +95.0°C)
```

We discussed that we want to read all the values. CPU, Package and Core. And stdout them all

**Comment by ribalba** [comment]
Instead of using the CPU filter we now want to gather all the temp data per chip. We expose this through the container_id

**Comment by ribalba** [comment]
@ArneTR ready for first review. Not everything is perfect but should work for a first review. Please install the `libglib2.0-0` and `libglib2.0-dev` packages before building. 

The original lm sensor files can be found under https://github.com/lm-sensors/lm-sensors/tree/master/prog/sensors

**Pull request merged**
