### PR TITLE
Env vars numbers tests

### PR DESCRIPTION
**Pull request by ArneTR**
Needed to make another PR as the test pipeline currently has a hickup.

This includes the fix from @davidkopp here: https://github.com/green-coding-berlin/green-metrics-tool/pull/541

Also I added tests and changed the logic of the env vars checking.

### CODE REVIEW

**Comment by ArneTR** [comment]
@dan-mm Can you please give this a look. You did not check the env vars in the skip case if not present, but just checked for exceptions.

Also you did not check if in allow_unsafe they were actually set.

please give it a look if I did not introduce an error.

**Comment by dan-mm** [comment]
it looks good to me, and I pulled and ran the tests locally - they all still pass.

based on the feedback from #545 I also extended the test_env_variable_no_skip_or_allow test into 3 tests, which check that each "unallowed" env var triggers a fail. This adds about +30 seconds to the test run though and I'm not convinced it provides enough added value, though it is better coverage. Should I check it in, or what are your thoughts?

**Comment by davidkopp** [comment]
I think it makes sense to use `dry_run=True` in the runner for the execution of these tests. The avoidance of the sleep saves a lot of time and the sleep is not relevant for testing if the env vars are correct or not.

**Comment by dan-mm** [comment]
That's a really good point actually - I had forgotten we had that flag. I just checked it with these specific tests and it cuts the time down to about a third. We could probably save a lot of time over our whole test suite by using this as the default - I'll make sure to check that. For now I just added it to these tests.

**Review by dan-mm — APPROVED** [review]

**Pull request merged**
