### PR TITLE
extends the install script to have a random password option

### PR DESCRIPTION
**Pull request by ribalba**

### CODE REVIEW

**Comment by ArneTR** [comment]
I like the idea and the implementation.

On a mac however I cannot generate random passwords:

```
./install_mac.sh
Please enter the desired API endpoint URL: (default: http://api.green-coding.internal:9142):
Please enter the desired metrics dashboard URL: (default: http://metrics.green-coding.internal:9142):
tr: Illegal byte sequence
Please enter the new password to be set for the PostgreSQL DB (default: B5):
```

This happens also when calling isolated: `tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 100`

**Review by ArneTR — CHANGES_REQUESTED** [review]
See comment

**Comment by ribalba** [comment]
@ArneTR please retest.

**Comment by ArneTR** [comment]
LGTM

**Pull request merged**
