### PR TITLE
Multi commit comparison

### PR DESCRIPTION
**Pull request by ArneTR**
If we monitor a repository over time we want to compare the multiple measurements over time in a consistent way.

This is a draft: https://metrics.green-coding.berlin/compare.html?ids=93eac1ba-d4da-4772-8b17-e2b8ca4eefbd,64a3cd4e-61e0-4d87-b4b0-2f4a14d3e298,0fac23a4-5bd9-467c-a12e-4770ced70ce9,43eadd1b-8afd-4710-a924-2730f5f5d555,ba01ae48-9cda-4ee6-9c1b-7a47c462644f,10b02501-34f9-42d1-861b-69de7586af7e,87469e25-7d94-41fb-99f8-556fef9fe2fa,1d4584e0-795f-4c04-b5fc-0becb0836a36,04cc4b3d-3b14-4be0-8ab3-0b181c3f4cb9,06c8f47b-7ac9-4057-ba10-a1857e08e237,3afa7cb8-ce6b-418f-bab2-04227a6c27f2,2b212814-1a71-4a29-b6e2-3b0a0bb0b4ef,0bc91b1c-e0b3-4428-b70c-40abca750cea,7bdacbda-46e2-4be8-9397-c3989bb081ed,c8fda085-1b2b-4d65-a383-3a4c7d38f991,8ea45224-b09e-44d8-9041-bab526bfdaa9,7209e166-0821-48d4-8421-5806e10d28f0,4f6ea303-31d0-4be5-81c6-f829508816e4,a4cff553-0296-42b5-ba0e-4afdd76c5e62,bc066f15-a3c3-41fc-b599-5964acbceb7a,ca7f451b-0af2-4dd5-a645-4ced1c11b54c,2fea43c9-e4a1-4156-8eb1-edca84ef7bde,46828fa3-ebdc-4c48-9d92-6210764253bd,84d06d25-c0fc-4dc0-b49c-8d7ffe330734,db425e9a-c675-4074-812e-9b2fbe83c6ae,7b9baed9-fac2-4392-a925-262240c0a1ef,016f80c7-b7e6-4a17-aad8-53310bb0b65a,67e90065-1907-48f0-adce-4c13ab7851b0,978710f1-05fc-45c5-8113-b5d66d54bbf2,fd3e821a-635b-49a3-aead-75e2fe3b8962,d85b4cd8-d700-4797-9ef7-6970fdb812a1,d35a07ac-e32e-4780-8561-eadf1bcc087d,0b586916-8d82-4b83-8722-037b487ed457,bdb5d6fc-3de2-4bd1-a719-37c499ccf55f,6d96178f-18f6-469a-bf91-2c2fe90f319c,1808c4c0-3de9-4413-92e3-f5fad8d9ffe9,b6cf97b0-0b29-4d27-86bd-0dd0fadf0e10,ce62ecc6-32d8-40c5-962b-0c245225c9e8,1a3904bc-cf48-4ced-9c1a-efb9e2e9d615,79931533-73d4-42ed-9598-03ca401857eb,5f8fcd57-711f-4717-bf75-1dc3224763f5

The comparison boxes make no sense anymore for this case, thus I do not fill them atm.

Up for debate ...

### CODE REVIEW

**Comment by ribalba** [comment]
The link doesn't work. Let's discuss tomorrow. I agree that we should not display the comparison boxes as they don't really add value except if you want to keep the repo usages the same which doesn't make sense. But what I would want to see is the overall trend. So let's say I am monitoring a repo I would want to see increase or decrease of usage in the last year/month.

**Comment by ribalba** [comment]
@ArneTR is still up for review? We talked about it but I am not sure if this is the code we discussed.

**Comment by ArneTR** [comment]
@ribalba No, sry. I removed you now from reviewers for clarity

**Comment by ArneTR** [comment]
The PR is now fully reworked and will display the Radar chart even when some metrics are missing in a comparison.

Also comparisons for machines are now possible if they contain different containers. Containers that have no match will just show undefined as pairing.

Examples are from: https://metrics.green-coding.berlin/compare.html?ids=284e0654-0193-41e8-afbf-36f38235dcdc,fb6e3e27-6391-495b-8454-920fa922cfda

Old:
Screenshot 2023-07-29 at 10 31 30 PM

New:
Screenshot 2023-07-29 at 10 32 09 PM

Missing container:
Screenshot 2023-07-29 at 10 57 25 PM



TODO: Comparison when different psu_energy_*_machine provider are selected, so for instance IPMI vs. PowerSpy2

**Comment by ArneTR** [comment]
I in the end decided against mapping different machine energy providers to a single "metric box".

The code is just too hacky and has too many tripwires in the end that I belive the benefit is less than the added complexity.

For instance:
- Why is only the machine energy mapped and not every other metric too? What happens if two different networ providers are registered
- What happens if one has three energy providers and the other two. Which one is then shown in the metric box and why?

In the new code one can see these comparisons directly in the bar-chart and the mappings are not done. Instead an "undefined" is shown to alert that the providers do not match.

I decided this is the cleanest solution.

Screenshot 2023-07-30 at 8 25 32 PM

**Pull request merged**
